Document
UCF-SeniorDesign-Mercury/Mercury-backend pull request #10
Opened 2021-12-23 22:46 UTC by TangyrenMidKing

All existing event endpoints are documented. 
- Post /create_event
- Delete /delete_event/{event_id}
- Get /get_event/{event_id}
- Get /get_next_event_page
- Get /get_recent_events
- Post /update_event

2022-01-10 22:42 UTC, Astatium5 requested changes

2022-01-10 22:42 UTC, Astatium5 commented on .gitignore
> +.firebaserc
No need to add these files to .gitignore. They don't contain any sensitive info and needed to run the Firebase Emulator Suite

2022-01-10 23:52 UTC, TangyrenMidKing commented on src/__main__.py
> -    app.run(host='0.0.0.0', port=int(environ.get("PORT", 8080)), debug=True)
oh, my bad, for get change it, it only for my local test.

2022-01-11 01:49 UTC, Astatium5 requested changes

2022-01-11 01:49 UTC, Astatium5 commented on src/schemas.yml
> +      example: Doctor
Add a blank line at the end of the file

2022-01-11 01:49 UTC, Astatium5 commented on src/api/roles.py
> +                            type: string
No response schema here

2022-01-11 01:49 UTC, Astatium5 commented on src/api/roles.py
> +            type: string
Add an example here

2022-01-11 01:49 UTC, Astatium5 commented on src/api/events.py
> +                    schema:
No response schema here

2022-01-12 01:41 UTC, Astatium5 approved these changes

2022-01-12 01:41 UTC, merged