Files
UCF-SeniorDesign-Mercury/Mercury-backend pull request #11
Opened 2022-01-14 04:28 UTC by TangyrenMidKing

the file script is fully tested without the auth and all works functionally on my local end. 
Please review it and give me some feedback.

2022-01-15 03:21 UTC, Astatium5 requested changes
Overall, looks good and we did pretty good progress. Needs some minor changes and maybe some more discussion

2022-01-15 03:21 UTC, Astatium5 commented on .dockerignore
> -Dockerfile
Why did you delete all Docker files? We still need them for deploying to the GCP thing

2022-01-15 03:21 UTC, Astatium5 commented on src/api/files.py
> +    # uid: str = str(uuid4())
Should be completely removed

2022-01-15 03:21 UTC, Astatium5 commented on src/api/files.py
> +    entry["comment"] = ""
I don't think you need to initialize it here, we need to create a separate endpoint for adding a review. But that's a good thing you mentioned it, I forgot that we need it

2022-01-15 03:21 UTC, Astatium5 commented on src/api/files.py
> +        # or decoded_token.get("admin") != True
Should remove comment and put `and` instead of `or`. Sorry, that's a bug from me

2022-01-15 03:21 UTC, Astatium5 commented on src/api/files.py
> +        or uid != data.get("author")
Should be `and` here

2022-01-15 03:21 UTC, Astatium5 commented on src/api/files.py
>          or decoded_token.get("admin") != True
Should be `and` here

2022-01-15 03:21 UTC, Astatium5 commented on src/api/files.py
> +def change_status():
I think `file_id` should be put as a parameter, it shouldn't be in the request data. Also, think that this endpoint should be called `add_review`, since it's basically doing that instead of just changing the status

2022-01-15 03:21 UTC, Astatium5 commented on src/__main__.py
> +CORS(app)
We need to add CORS policies. You can mark it unresolved right away, just want to keep it in this discussion too

2022-01-15 03:21 UTC, Astatium5 commented on src/api/files.py
> +    # Expcetions
"Exceptions"

2022-01-15 03:21 UTC, Astatium5 commented on src/api/files.py
> +    if data["decision"] < 3 or data["decision"] >5:
Should be a space after `>` in `>5`. Please, install and configure the Black formatter and it will take care of it for you

2022-01-15 03:21 UTC, Astatium5 commented on src/api/files.py
> +        or decoded_token.get("admin") != True
I think it should be `and` here too

2022-01-15 03:21 UTC, Astatium5 commented on src/api/files.py
> +    user_ref = db.collection(u"User").document(uid)
You can mark it resolved right away too, but we need to add lines like that to every endpoint, not only this one. Will do it in the future PRs

2022-01-15 03:21 UTC, Astatium5 commented on src/api/files.py
> +from io import BytesIO, UnsupportedOperation
Don't think we need this import since it's not used anywhere. Also, need to clean all imports in the future PRs

2022-01-15 03:21 UTC, Astatium5 commented on src/api/files.py
> +from xmlrpc.client import boolean
Don't think we need this import too

2022-01-16 04:26 UTC, TangyrenMidKing commented on src/api/files.py
> +def change_status():
It does change the status at this endpoint by line 270. 
Also, I need 3 things to pass from the frontend, it's easier to put all the things in one place either the header parameter or the request body. Do you have a specific reason why you want to keep the file_id in the header parameter?

2022-01-16 04:31 UTC, closed without merging