Files, Events Refactored
UCF-SeniorDesign-Mercury/Mercury-backend pull request #15
Opened 2022-01-21 20:21 UTC by TangyrenMidKing

Event:
cancel_register/{event_id}
change_status
create_event
delete_event​/{event_id}
get_event/{event_id}
get_next_event_page
get_recent_events
register_event/{event_id}
update_event

Files:
change_status
delete_file/{file_id}
get_file/{file_id}
update_file
upload_file

2022-01-26 22:38 UTC, Astatium5 commented on src/api/events.py
> +    # if enevt does not exists
"event"

2022-01-26 22:38 UTC, Astatium5 commented on firestore.rules
> +		// match /Scheduled-Events/{events} {
Remove comments

2022-01-26 22:38 UTC, Astatium5 commented on src/api/events.py
> +    # if enevt does not exists
"event"

2022-01-26 22:38 UTC, Astatium5 commented on src/api/events.py
> +        return Response("The event close for register", 403)
"is closed for registration"
Also, it should return a `Forbidden` exception imported from `werkzeug.exceptions`

2022-01-26 22:38 UTC, Astatium5 commented on src/api/events.py
> +        return Response("The event no longer exists", 404)
Should be `NotFound` from `werkzeug.exceptions`

2022-01-26 22:38 UTC, Astatium5 commented on src/api/events.py
> +        return Response("The event no longer exists", 404)
Should be `NotFound` from `werkzeug.exceptions`

2022-01-26 22:38 UTC, Astatium5 commented on src/api/events.py
> +        return Response("Unsupported decision type", 400)
Should be `BadRequest` from `werkzeug.exceptions`

2022-01-26 22:38 UTC, Astatium5 commented on src/api/files.py
> +        return Response("The file not found", 404)
Should be `NotFound` from `werkzeug.exceptions`

2022-01-26 22:38 UTC, Astatium5 commented on src/api/files.py
> +        return Response(
Should be `NotFound` from `werkzeug.exceptions`

2022-01-26 22:38 UTC, Astatium5 commented on src/schemas.yml
> +    participators:
"participants"

2022-01-26 22:38 UTC, Astatium5 commented on src/schemas.yml
> +      example: The organier name
"organizer"

2022-01-26 22:38 UTC, Astatium5 commented on src/api/files.py
> +            raise BadRequest("cannot update to storage")
Looks like this is not a `BadRequest`, but maybe an `InternalServerError`. Not sure though, need to look at possible exceptions, which could be thrown by Storage

2022-01-26 22:38 UTC, Astatium5 commented on src/api/files.py
> +        uid != data["reviewer"]
Better stick with `.get()` for every retrieval from a dictionary operation. You can read more about it here (in the comparison section): *[link](https://www.programiz.com/python-programming/methods/dictionary/get)*

2022-01-26 22:38 UTC, Astatium5 commented on src/api/events.py
> +        return Response(response="Event no longer exist", status=404)
Should be `NotFound` from `werkzeug.exceptions`

2022-01-26 22:38 UTC, Astatium5 commented on src/api/events.py
> +        return Response("The event not found", 404)
Should be `NotFound` from `werkzeug.exceptions`

2022-01-26 22:38 UTC, Astatium5 commented on src/api/events.py
> +        return Response("The event not found", 404)
Should be `NotFound` from `werkzeug.exceptions`

2022-01-27 03:45 UTC, Astatium5 requested changes

2022-01-27 03:45 UTC, Astatium5 commented on src/api/events.py
> +        return NotFound("The event not found", 404)
Not need to specify the response code, it is embedded in the exception itself. Same goes with every exception from `werkzeug.exceptions`

2022-01-27 18:30 UTC, TangyrenMidKing commented on src/api/events.py
> +        return NotFound("The event not found", 404)
I will change it asap, I need to go over the descriptions in the comments and change it.

2022-01-28 04:01 UTC, Astatium5 approved these changes

2022-01-28 04:01 UTC, merged