Events
UCF-SeniorDesign-Mercury/Mercury-backend pull request #21
Opened 2022-02-22 01:07 UTC by TangyrenMidKing

refactored the event api

2022-02-25 18:36 UTC, Astatium5 requested changes

2022-02-25 18:36 UTC, Astatium5 commented on src/api/files.py
>  def get_next_event_page() -> Response:
Change function name to `review_user_files`

2022-02-26 00:19 UTC, TangyrenMidKing commented on pyproject.toml
> +name = "mercury-backend-dev"
no, this shouldn't be changed, it's just for my mock server to host.

2022-02-26 00:22 UTC, TangyrenMidKing commented on src/api/events.py
> +    # Only the event user could delete the event
This event object is private now. what private means is that only visible by the creator.  The event right now is like a calendar reminder. Create by user self, and only visible by user self.

2022-02-26 00:41 UTC, Astatium5 approved these changes

2022-02-26 00:41 UTC, merged