Mercury dev
UCF-SeniorDesign-Mercury/Mercury-backend pull request #26
Opened 2022-03-25 12:55 UTC by TangyrenMidKing

The medical data module was completed. 
Minor changes on get_uers base on Josh's request. 
Readme file adds the active python env, and active debug model.

Please review it after March 25.

2022-03-30 12:51 UTC, Astatium5 requested changes

2022-03-30 12:51 UTC, Astatium5 commented on src/api/medical.py
> +        if not medical_ref.get().exists:
Are you sure that this is correct? In my understanding, `.get()` should not be here, but I am not sure

2022-03-30 12:52 UTC, Astatium5 commented on README.md
> +export FLASK_ENV=development
These two lines can be changed to:
```bash
export FLASK_ENV=development && poetry run python -m src run --port=5000
```

2022-04-02 14:40 UTC, TangyrenMidKing commented on src/api/medical.py
> +        if not medical_ref.get().exists:
Yeah, the medical_ref needs a .get() to transform it to the python readable object.

2022-04-03 02:15 UTC, Astatium5 approved these changes

2022-04-03 02:15 UTC, merged